apiVersion: apps/v1
kind: Deployment
metadata:
  name: neopost-depl
  labels:
    app: neopost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neopost
  template:
    metadata:
      labels:
        app: neopost
    spec:
      containers:
        - name: neopost
          image: anshumanc6/ceaa-backend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: neopost-srv
spec:
  selector:
    app: neopost
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

